export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const SHOW_ALL_PRODUCT_SUCCESS = 'SHOW_ALL_PRODUCT_SUCCESS'
export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_TO_CART = 'REMOVE_TO_CART'
export const INCREAMENT_QTY ="INCREAMENT_QTY"
export const DECREAMENT_QTY = "DECREAMENT_QTY"